[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "librosa",
    "playsound",
    "pygame>=2.6.1",
    "replit",
]
